apiVersion: v1
kind: Service
metadata:
  name: {{ include "privoxy-vpn.fullname" . }}
  labels:
    {{- include "privoxy-vpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "privoxy-vpn.selectorLabels" . | nindent 4 }}
